//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int applicantId { get; set; }
        public string salaryExpected { get; set; }
        public string fullTimeYN { get; set; }
        public string daysYN { get; set; }
        public string eveningsYN { get; set; }
        public string weekendsYN { get; set; }
        public Nullable<System.TimeSpan> mondayFrom { get; set; }
        public Nullable<System.TimeSpan> mondayTo { get; set; }
        public Nullable<System.TimeSpan> tuesdayFrom { get; set; }
        public Nullable<System.TimeSpan> tuesdayTo { get; set; }
        public Nullable<System.TimeSpan> wednesdayFrom { get; set; }
        public Nullable<System.TimeSpan> wednesdayTo { get; set; }
        public Nullable<System.TimeSpan> thursdayFrom { get; set; }
        public Nullable<System.TimeSpan> thursdayTo { get; set; }
        public Nullable<System.TimeSpan> fridayFrom { get; set; }
        public Nullable<System.TimeSpan> fridayTo { get; set; }
        public Nullable<System.TimeSpan> saturdayFrom { get; set; }
        public Nullable<System.TimeSpan> saturdayTo { get; set; }
        public Nullable<System.TimeSpan> sundayFrom { get; set; }
        public Nullable<System.TimeSpan> sundayTo { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
