//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int applicantId { get; set; }
        public int educationId { get; set; }
        public string name { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string stateAbrev { get; set; }
        public string zip { get; set; }
        public string yearFrom { get; set; }
        public string yearTo { get; set; }
        public string graduatedYN { get; set; }
        public string degreeMajor { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
