//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int applicantId { get; set; }
        public string personalInfoNotes { get; set; }
        public string educationNotes { get; set; }
        public string referenceNotes { get; set; }
        public string jobHistoryNotes { get; set; }
        public string availabilityNotes { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
